Lambda-School-Labs/ping-catcher-fe

.github/workflows/ci.yml
package.json
src/App.test.js

Closes [First test for setting up code coverage](https://trello.com/c/2sZCK7Am/49-first-test-for-setting-up-code-coverage)
- add `test:watch` to package.json `scripts` key
- add `coverage` to package.json `scripts` key
- configure `jest` key in package.json
- create `ci.yml` file for CI
- add `CODECLIMATEREPORTERID` secret to GitHub repo [@debauchery1st ]
To test: 
- Clone the repo
- Make a commit
- Push the changes to trigger a coverage test
`ci.yml` has been configured to use `yarn` instead of `npm`.

#49-first-test-for-setting-up-code-coverage

---

src/App.js
src/components/Login.js

added login route to start working on Okta front-end
feature
yarn start

added login component to start testing okta on the front-end

---

src/App.jsx

Added route code splitting for app.js
yarn start

added route code splitting on app.jsx

---

src/Home.jsx

Added a note to help with communicating with the back-end

added a todo note to communcate with the backend

---

src/config.js

login redirect address was different than the current website address, replaced with new address.
okta login redirect uri bug

config.js needed new ping-catcher.com address to redirect uri

---

src/config.js

using environment variables to post callback urls

---

config-overrides.js

local dev environment reads from .env

fixed config-overrides to point to .env file

---

src/App.jsx
src/Home.jsx
src/Navbar.jsx
src/components/Spinner.js

dashboard button only displays once logged in, ping catcher images leads to home page
yarn start

changed dashboard button to only display once logged in

---

src/App.jsx
src/components/PingCard.js
src/components/SlackEvents.js

styles to dashboard
style
yarn start

added styles to dashboard

---

src/components/ImageSpinner.jsx

re-usable component, ImageSpinner

---

src/components/ImageSpinner.jsx

return spinner when not loaded.

fixed. return spinner when not loaded.

---

src/AppDrawer.jsx

Deleted about 34 lines of code. Removed imports that weren't being used.

Cleaned up code

---

src/App.jsx
src/AppDrawer.jsx
src/AppDrawerNew.jsx
src/components/Drawer.jsx

Switched over to the Responsive Drawer, and made a list into it's own component.

Switched to responsive drawer

---

package-lock.json
package.json
src/App.jsx
src/components/RankingForm.js
src/components/SlackEvents.js
src/components/navbar/AppDrawer.jsx
yarn.lock

Relocate routes to AppDrawer Component
Feature.
yarn start

relocated routes to AppDrawer on ResponsiveDrawer

---

src/components/RankingForm.js

Ranking Form
Feature
yarn start

created rankings form with Material UI and React Hook Forms

---

src/App.jsx

Added comments to App.js to explain what happens and TODO list

---

src/App.jsx
src/components/dashboard/subPanels/dashboard/Dashboard.js

Added ranking form route
yarn start

added ranking form route

---

src/Old_Components/RankingForm.js

added icon and form field 'nickname'
yarn start

Style added form field

---

src/App.test.jsx
src/components/dashboard/dashboardPage/DashbordPage.test.js
src/index.js

Second Test written and passing!

Second test passing!

---

src/App.jsx
src/components/RankingForm.js
src/components/SlackCallback.js
src/components/dashboard/dashboardPage/DashboardPage.js
src/components/dashboard/subPanels/useStateWithLocalStorage.js
src/components/landingPage/hero/Hero.js
src/components/landingPage/navbar/Navbar.js

Got the slack callback working

The slack callback url is working and grabbing the url

---

src/App.jsx
src/components/SlackSignIn.js
src/components/dashboard/subPanels/profile/Profile.js
src/index.css

okta login reroutes to slack log in route.
feature
yarn start

feature-reroute-to-slack-signin

---

src/App.jsx
src/components/SlackCallback.js
src/components/slackInfo/TokenRequest.js

removed console.logs with sensitive info
privacy
yarn start

removed console.logs with sensitive info

---

src/App.jsx
src/components/RankingForm.js
src/components/dashboard/dashboardPage/DashboardPage.js
src/components/dashboard/subPanels/subscriptionForm/SubscriptionForm.js

tied slack id to form
feature
yarn start

set up form to push slackId with form

---

src/components/dashboard/subPanels/dashboard/Dashboard.js

removed .js from snooz
yarn start

removed js from snooze

---

src/components/dashboard/subPanels/dashboard/Dashboard.js

captial letter snooze
aws deployment

fixed snooze capital letter

---

.gitignore
src/components/dashboard/subPanels/dashboard/Dashboard.js

Windows & Case Sensitive File Names.
renaming Snooze.js to snooze.js wasn't registering.
updating filename from POSIX compliant system. (GNU/Linux)

fixed case-sensitive file name import

---

src/components/dashboard/subPanels/dashboard/Dashboard.js
src/components/slackInfo/snooze.js

fixed issue with snooze throwing cors error by fixing the url
fixed url from slack test example
bug fix
yarn start

fixed url on snooze component

---

src/components/slackInfo/snooze.js

added end snooze button and functionality
fixed warning about useEffect not being used
feature
- yarn start

implemented an end snooze button and functionality

---

src/App.jsx
src/components/MembersList.js
src/components/dashboard/dashDrawer/SettingDrawer.js
src/components/dashboard/dashDrawer/SubDrawer.js
src/components/dashboard/dashboardPage/DashboardPage.js
src/components/dashboard/subPanels/dashboard/Dashboard.js

mobile ready drawer component
feature
- yarn start

created responsive drawer, needs more work

---

package.json
src/components/EventCard.test.js
src/components/MembersList.js
src/components/MembersList.test.js
src/components/PingCard.test.js
src/components/RankingForm.js
src/components/RankingForm.test.js
src/components/dashboard/subPanels/SubPanel.test.js
yarn.lock

Added some more tests. Need to work on more tests. One of them refused to pass. Can't figure that one out. Going to look over it more.

wrote some more tests

---

src/components/MembersList.js

undefined state variable, memberlist, interrupts pageload.

fix: undefined array breaks pageload

---

src/components/SlackCallback.js
src/components/dashboard/dashDrawer/SettingDrawer.js
src/components/dashboard/dashDrawer/SubDrawer.js
src/components/dashboard/dashboardPage/DashboardPage.js
src/components/landingPage/footer/footer.css
src/components/landingPage/infoCard/NotifyCard.js
src/components/landingPage/infoCard/OrganizeCard.js
src/components/landingPage/infoCard/SlackCard.js
src/components/landingPage/navbar/Navbar.js
src/components/landingPage/page/LandingPage.jsx

added media queries and styles to slackCard
feature
-yarn start

added some styling to slackCard, added 1 media querie

---

src/components/EventCard.js
src/components/PingCard.js

Auto Update Events
Feature
- yarn start

modified eventCard for useEffect to autoUpdate

---

src/components/EventCard.js

removed events from useEffect

---

src/App.jsx
src/components/landingPage/footer/footer.css
src/components/landingPage/infoCard/NotifyCard.js
src/components/landingPage/infoCard/OrganizeCard.js
src/components/landingPage/infoCard/SlackCard.js
src/components/landingPage/page/LandingPage.css
src/components/landingPage/page/LandingPage.jsx

Changed the background color of the landing page.

---

src/components/dashboard/dashDrawer/SettingDrawer.js
src/components/dashboard/dashNav/DashboardNav.js
src/components/dashboard/dashNav/dashNavComponents/NavContent.jsx
src/components/dashboard/dashboardPage/DashboardPage.js
src/components/dashboard/subPanels/dashboard/Dashboard.js

created menu to be mobile responsive

---

main.css
src/components/landingPage/hero/hero.css
src/components/landingPage/page/LandingPage.css

fixed lightCoral color on landing page
style
- yarn start

changed lightCoral from landing page on @media

---

src/components/EventCard.js
src/components/MembersList.js

removed token from membersList and added console.log

removed token from memberlist useEffect dependencies

---

src/components/SlackCallback.js

more testing
